### PR TITLE
Updated node for lock tokens feature

### PR DESCRIPTION
**Pull request by evlekht**

### CODE REVIEW

**Comment by evlekht** [comment]
https://github.com/chain4travel/caminogo/pull/6
Related to this feature

**Comment by DerTiedemann** [comment]
This PR does not build atm, pls fix @evlekht.

**Comment by evlekht** [comment]
> This PR does not build atm, pls fix @evlekht.

Yea, cause it depends on changes in camingo, which aren't pushed yet and don't have version, so I can't update dependency
That's why its draft :)

**Comment by c4t-ag** [comment]
@evlekht pls. fix and only add missibg CaminoConfig

**Pull request closed without merging**
